services:
  keycloak:
    build:
      context: ./docker-compose/data/keycloak
    container_name: keycloak
    volumes:
      - ./docker-compose/data/keycloak/realm:/opt/jboss/keycloak/imports
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_SPI_INITIALIZER_ISSUER_BASE_URI: http://keycloak:8080
      KC_HEALTH_ENABLED: "true"
    command: [ "start-dev", "--import-realm" ]
    healthcheck: # check the endpoint for a valid response (service ready)
      test: [
        "CMD-SHELL",
        'exec 3<>/dev/tcp/localhost/8080; echo -e "GET /health/ready HTTP/1.1\nhost: localhost:8080\n" >&3; timeout --preserve-status 1 cat <&3 | grep -m 1 status | grep -m 1 UP; ERROR=$?; exec 3<&-; exec 3>&-; exit $ERROR'
      ]
      interval: 30s
      timeout: 10s
      retries: 6
    networks:
      - mnestix-network

  aas-environment:
    environment:
      # Authorization
      basyx.feature.authorization.enabled: "true"
      basyx.feature.authorization.type: rbac
      basyx.feature.authorization.jwtBearerTokenProvider: keycloak
      basyx.feature.authorization.rbac.file: file:/data/rbac_rules.json
      spring.security.oauth2.resourceserver.jwt.issuer-uri: "http://keycloak:8080/realms/BaSyx"
    volumes:
      - ./docker-compose/data/keycloak/rbac_rules.json:/data/rbac_rules.json:ro

  mnestix-browser:
    environment:
      AUTHENTICATION_FEATURE_FLAG: "true"
      NEXTAUTH_URL: "http://localhost:3000"
      KEYCLOAK_ENABLED: "true"
      KEYCLOAK_CLIENT_ID: "mnestix-browser-client-demo"
      KEYCLOAK_ISSUER: "http://keycloak:8080"
      KEYCLOAK_LOCAL_URL: "http://localhost:8080"
      KEYCLOAK_REALM: "BaSyx"

  mnestix-api:
    environment:
      Features__UseAuthentication: "true"
      # OpenId repository settings
      RepositoryOpenIdConnect__EnableRepositoryOpenIdAuth: "true"
      RepositoryOpenIdConnect__Authority: "http://keycloak:8080/realms/BaSyx"
      RepositoryOpenIdConnect__DiscoveryEndpoint: ".well-known/openid-configuration"
      RepositoryOpenIdConnect__ClientId: "mnestix-repo-client-demo"
      RepositoryOpenIdConnect__ClientSecret: ${REPOSITORY_API_CLIENT_SECRET:-WLOB68nSllHTlr7ViUOZWWxildWFT2nN}
      RepositoryOpenIdConnect__ValidateIssuer: "false"
      RepositoryOpenIdConnect__TokenEndpoint: "http://keycloak:8080/realms/BaSyx/protocol/openid-connect/token"
      # OpenID Configuration
      OpenId__EnableOpenIdAuth: "true"
      OpenId__Issuer: "http://keycloak:8080/realms/BaSyx"
      OpenId__ClientID: "mnestixApi-demo"
      OpenId__RequireHttpsMetadata: "false"
    depends_on:
      keycloak:
        condition: service_healthy