# values.yaml

# Number of replicas of the application to be deployed
replicaCount: 1

# Docker image details
image:
  repository: mnestix/mnestix-browser
  pullPolicy: IfNotPresent
  tag: latest
  pullSecrets: []

# Kubernetes Service settings
service:
  type: LoadBalancer
  port: 80

# Ingress settings for exposing the service (optional)
# ingress:
#   enabled: false
#   annotations: {}
#   hosts:
#     - host: chart-example.local
#       paths:
#         - /
#   tls: []

# Resource requests and limits for the application pods
resources:
  limits:
    cpu: '500m'
    memory: '512Mi'
  requests:
    cpu: '250m'
    memory: '256Mi'

# Autoscaling settings (optional)
# autoscaling:
#   enabled: false
#   minReplicas: 1
#   maxReplicas: 10
#   targetCPUUtilizationPercentage: 80

# Node selector to constrain pods to nodes with specific labels (optional)
nodeSelector: {}

# Tolerations to allow pods to run on tainted nodes (optional)
tolerations: []

# Affinity rules to influence pod scheduling (optional)
affinity: {}

# Enable ingress for release name
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

env:
  REGISTRY_API_URL: 'https://aas.my.murrelektronik.de/api/aas-registry'
  DISCOVERY_API_URL: 'https://aas.my.murrelektronik.de/api/discovery'
  AAS_REPO_API_URL: 'https://aas.my.murrelektronik.com/api'
  MNESTIX_BACKEND_API_URL: 'http://staging-iiot-api-gateway.iiot.dev.my.yacoub.de'
  AD_CLIENT_ID: ${AD_CLIENT_ID}
  AD_TENANT_ID: ${AD_TENANT_ID}
  APPLICATION_ID_URI: 'api://mnestix-test-web-api/'
  AAS_LIST_FEATURE_FLAG: true
  COMPARISON_FEATURE_FLAG: true
  AUTHENTICATION_FEATURE_FLAG: true
  LOCK_TIMESERIES_PERIOD_FEATURE_FLAG: true
  THEME_PRIMARY_COLOR: '#3DB60F'
  THEME_SECONDARY_COLOR: '#37A40D'
  #      THEME_LOGO_MIME_TYPE: 'image/svg+xml'
  THEME_LOGO_URL: '/images/murr-company-logo.png'
